<div style="text-align: left;">
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" alt="Image description" width="50%"/>
</div>

<p style="font-family:Helvica; font-size:26px; ">
<b>What is NumPy?</b>
</p>

<p style="font-family:Helvica; font-size:20px; ">
NumPy (Numerical Python) is a powerful library in Python used for numerical and scientific computing. It provides support for arrays, matrices, and many mathematical functions that operate on these data structures. Here's why it's significant:
</p>
<p style="font-family:Helvica; font-size:20px; ">
1.<b> N-dimensional Array (ndarray):</b> The core of NumPy is its ndarray object, which provides fast and memory-efficient array operations compared to native Python lists. This array can be one-dimensional (vectors), two-dimensional (matrices), or even higher dimensions.    </p>
<p style="font-family:Helvica; font-size:20px; ">
2. <b>Broadcasting:</b> NumPy allows you to perform operations on arrays of different shapes, which automatically "broadcasts" the smaller array over the larger one, making the code cleaner and more efficient.    </p>
<p style="font-family:Helvica; font-size:20px; ">
3. <b>Vectorization:</b> This means you can apply operations to entire arrays without explicit loops. This not only simplifies code but makes it much faster because NumPy is implemented in C, allowing for optimized performance.    </p>
<p style="font-family:Helvica; font-size:20px; ">    
4.<b> Mathematical Operations:</b> NumPy provides a wide range of mathematical functions (like trigonometric functions, linear algebra operations, statistics, etc.) that are fast and efficient.    </p>

<p style="font-family:Helvica; font-size:20px; ">
    5. <b>Integration with Other Libraries:</b> NumPy is the foundational library for many other libraries in the Python ecosystem, including:
    <li style="font-family:Helvica; font-size:20px;"> Pandas (for data analysis)</li>
    <li style="font-family:Helvica; font-size:20px;"> Matplotlib (for plotting)</li>
    <li style="font-family:Helvica; font-size:20px;"> Scikit-learn (for machine learning)</li>
    <li style="font-family:Helvica; font-size:20px;"> TensorFlow, PyTorch (for deep learning)</li>
    </p>
<p style="font-family:Helvica; font-size:20px; "> These libraries are built around NumPy arrays or have APIs that are compatible with NumPy.</p>

<p style="font-family:Helvica; font-size:26px; ">
<b>Why is NumPy Useful?</b>
</p>

<p style="font-family:Helvica; font-size:20px; ">
1.<b> Performance:</b> NumPy is much faster than Python lists for numerical computations. This is because it is implemented in C and optimized for performance.
</p>
<p style="font-family:Helvica; font-size:20px; ">
2.<b> Memory Efficiency:</b> NumPy uses less memory than native Python lists, which is critical when dealing with large datasets in data science and machine learning.
</p>
<p style="font-family:Helvica; font-size:20px; ">
3.<b> Convenience:</b> Operations on arrays, such as element-wise addition, multiplication, reshaping, and slicing, are simple and efficient with NumPy. This makes it very convenient for writing clean, easy-to-read code.
</p>
<p style="font-family:Helvica; font-size:20px; ">
4.<b> Multi-dimensional Data:</b> NumPy supports multi-dimensional data, which is important when working with matrices, tensors, or large data sets in machine learning and scientific computing.
</p>
<p style="font-family:Helvica; font-size:20px; ">
5.<b> Data Manipulation:</b> You can easily perform complex mathematical operations like matrix multiplication, transposition, and Fourier transformations, making it essential for anyone working in fields like linear algebra, image processing, and signal processing.
</p>
<p style="font-family:Helvica; font-size:20px; ">
6.<b> Support for Large Data Sets:</b> As a data scientist or machine learning expert, you'll often be working with large data sets that need efficient storage and fast operations, and NumPy is designed for this.
</p>

<p style="font-family:Helvica; font-size:20px; ">
<b>Example</b>
<br/>Here's a simple example of using NumPy to demonstrate some of its benefits:
</p>

In [11]:
import numpy as np

# Create a 2x2 matrix
A = np.array([[1, 2], [3, 4]])

# Perform element-wise operations
B = A + 10  # Add 10 to each element
C = A * 2   # Multiply each element by 2

# Matrix multiplication
D = np.dot(A, C)

# Transpose of the matrix
E = A.T

# Output results
print("Matrix A:\n", A)
print("Matrix B (A + 10):\n", B)
print("Matrix C (A * 2):\n", C)
print("Matrix D (A dot C):\n", D)
print("Transpose of A:\n", E)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B (A + 10):
 [[11 12]
 [13 14]]
Matrix C (A * 2):
 [[2 4]
 [6 8]]
Matrix D (A dot C):
 [[14 20]
 [30 44]]
Transpose of A:
 [[1 3]
 [2 4]]


<p style="font-family:Helvica; font-size:20px; ">
This example shows how NumPy makes mathematical operations on arrays easy and intuitive.
</p>

<p style="font-family:Helvica; font-size:20px; ">
<b>Difference between NumPy arrays and Python lists.</b>
</p>

<p style="font-family:Helvica; font-size:20px; ">
The difference between NumPy arrays and Python lists lies mainly in their efficiency, speed, and the kinds of operations they support. Let’s break it down:</p>
<p style="font-family:Helvica; font-size:20px; ">
1.<b> Memory Efficiency</b>
<li style="font-family:Helvica; font-size:20px;">Python Lists:</li>
<p style="font-family:Helvica; font-size:20px; ">
Python lists are more flexible but less efficient in terms of memory. Each element in a Python list is a complete object with overhead.
Lists are pointers to objects, so storing numerical data (like integers or floats) requires more memory because each element in the list is a reference to a full Python object, not just the raw data.
</p>
<li style="font-family:Helvica; font-size:20px;">NumPy Arrays:</li>
<p style="font-family:Helvica; font-size:20px; ">
NumPy arrays store data more compactly. They are stored in contiguous blocks of memory, allowing for more efficient storage.
Instead of each element being a reference to a separate object, NumPy arrays store the raw numerical data directly. This leads to reduced memory overhead.
NumPy arrays are also homogeneous, meaning all elements must be of the same type (e.g., all floats or all integers), which contributes to memory efficiency.
</p>
<p style="font-family:Helvica; font-size:20px; ">
<b>Example of Memory Usage Comparison:</b>
</p>

In [2]:
import numpy as np
import sys

# Python list
py_list = [i for i in range(1000)]
print("Memory used by Python list:", sys.getsizeof(py_list))

# NumPy array
np_array = np.array(py_list)
print("Memory used by NumPy array:", np_array.nbytes)


Memory used by Python list: 8856
Memory used by NumPy array: 4000


<p style="font-family:Helvica; font-size:20px; ">
This shows that for large datasets, NumPy arrays require significantly less memory compared to Python lists.
</p>

<p style="font-family:Helvica; font-size:20px; ">
2.<b> Speed of Operations</b>
<li style="font-family:Helvica; font-size:20px;">Python Lists:</li>
<p style="font-family:Helvica; font-size:20px; ">
Python lists are slower because they are dynamically typed, meaning that Python has to determine the data type of each element during execution, which slows down computation.
Operations on lists, especially element-wise operations, often require looping through elements, which is not very efficient in Python.
</p>
<li style="font-family:Helvica; font-size:20px;">NumPy Arrays:</li>
<p style="font-family:Helvica; font-size:20px; ">
NumPy arrays are much faster because they are implemented in C and make use of highly optimized C libraries for mathematical operations.
With vectorized operations, NumPy allows you to perform operations on entire arrays at once without the need for loops. This results in much faster performance for numerical computations.
</p>
<p style="font-family:Helvica; font-size:20px; ">    
<b>Example of Speed Comparison:</b>
</p>
<p style="font-family:Helvica; font-size:20px; "> 
Let’s compare the speed of squaring elements in a Python list vs. a NumPy array.
</p>

In [3]:
import numpy as np
import time

# Python list
py_list = list(range(1000000))

# NumPy array
np_array = np.array(py_list)

# Squaring using Python list
start_time = time.time()
py_list_squared = [x**2 for x in py_list]
print("Time taken by Python list: %s seconds" % (time.time() - start_time))

# Squaring using NumPy array
start_time = time.time()
np_array_squared = np_array ** 2
print("Time taken by NumPy array: %s seconds" % (time.time() - start_time))


Time taken by Python list: 0.15839123725891113 seconds
Time taken by NumPy array: 0.0010018348693847656 seconds


<p style="font-family:Helvica; font-size:20px; "> 
This example shows that NumPy arrays are much faster than Python lists for element-wise operations.
</p>

<p style="font-family:Helvica; font-size:20px; ">
3.<b> Mathematical and Vectorized Operations</b>
<li style="font-family:Helvica; font-size:20px;">Python Lists:</li>
<p style="font-family:Helvica; font-size:20px; "> 
Python lists require looping through each element if you want to perform mathematical operations, and operations like matrix multiplication or trigonometric functions are not directly supported.
<li style="font-family:Helvica; font-size:20px;">NumPy Arrays:</li>
<p style="font-family:Helvica; font-size:20px; "> 
NumPy arrays support element-wise operations directly, which makes them much more convenient for mathematical and numerical work.
NumPy also supports vectorized operations, meaning you can apply a mathematical function over an entire array without explicitly writing loops.
<p style="font-family:Helvica; font-size:20px; "> 
<b>Example of Element-wise Operation:</b>

In [5]:
# Python list (manual loop)
py_list = [1, 2, 3, 4, 5]
py_result = [x + 10 for x in py_list]  # Need to use a loop

# NumPy array (vectorized operation)
np_array = np.array(py_list)
np_result = np_array + 10  # Vectorized operation

print("Python list result:", py_result)
print("NumPy array result:", np_result)


Python list result: [11, 12, 13, 14, 15]
NumPy array result: [11 12 13 14 15]


<p style="font-family:Helvica; font-size:20px; "> 
Here, the NumPy operation is simpler, faster, and more concise.

<p style="font-family:Helvica; font-size:20px; ">
4.<b> Homogeneity</b>
<li style="font-family:Helvica; font-size:20px;">Python Lists:</li>
<p style="font-family:Helvica; font-size:20px; ">
Python lists can store elements of different data types (e.g., integers, strings, floats), which makes them versatile but less efficient for numerical operations.
<li style="font-family:Helvica; font-size:20px;">NumPy Arrays:</li>
<p style="font-family:Helvica; font-size:20px; ">
NumPy arrays are homogeneous, meaning all elements must be of the same data type (e.g., all integers or all floats). This is a key reason why NumPy is more efficient for large-scale numerical computation.
<p style="font-family:Helvica; font-size:20px; ">
5.<b> Built-in Functions and Support</b>
<li style="font-family:Helvica; font-size:20px;">Python Lists:</li>
<p style="font-family:Helvica; font-size:20px; ">
Python lists have limited built-in support for numerical operations. You need to use Python loops or external libraries (like math or itertools) to perform operations on list elements.
<li style="font-family:Helvica; font-size:20px;">NumPy Arrays:</li>
<p style="font-family:Helvica; font-size:20px; ">
NumPy provides a rich set of built-in functions for numerical computations such as linear algebra, Fourier transforms, statistics, and random number generation. These functions are highly optimized and allow for efficient computation.
<p style="font-family:Helvica; font-size:20px; ">
<b>Conclusion:</b>
<p style="font-family:Helvica; font-size:20px; ">
<ul style="font-family:Helvica; font-size:20px;">NumPy arrays are highly efficient for numerical computations due to their compact memory usage and fast execution, especially for large datasets and multi-dimensional arrays.</ul>
<ul style="font-family:Helvica; font-size:20px;">Python lists are more general-purpose but are slower and less memory efficient when performing mathematical operations on large amounts of data.</ul>
<p style="font-family:Helvica; font-size:20px; ">
For data science, machine learning, or any performance-critical numerical tasks, NumPy arrays are a much better choice than Python lists.

<p style="font-family:Helvica; font-size:20px; ">
<b>Data Types and Attributes in NumPy</b>
<p style="font-family:Helvica; font-size:20px; ">
Understanding data types (dtype) and some important attributes of NumPy arrays is crucial for efficient numerical computation.
<p style="font-family:Helvica; font-size:20px; ">
1.<b> Understanding dtype (Data Type)</b>
<p style="font-family:Helvica; font-size:20px; ">
In NumPy, each array has a data type (dtype), which defines the type of elements stored in the array. This is important because NumPy arrays are homogeneous, meaning all elements must be of the same data type.
<p style="font-family:Helvica; font-size:20px; ">
<ul style="font-family:Helvica; font-size:20px;"><b>Common NumPy Data Types:</b>
<li style="font-family:Helvica; font-size:20px;">int32, int64: Signed integers of 32 or 64 bits.</li>
<li style="font-family:Helvica; font-size:20px;">float32, float64: Floating-point numbers (single or double precision).</li>
<li style="font-family:Helvica; font-size:20px;">complex128: Complex numbers.</li>
<li style="font-family:Helvica; font-size:20px;">bool: Boolean values (True or False).</li>
<li style="font-family:Helvica; font-size:20px;">object: Python objects.</li>
<li style="font-family:Helvica; font-size:20px;">string: Fixed-length strings.</li>
<li style="font-family:Helvica; font-size:20px;">datetime64: Dates and times.</li></ul>
<p style="font-family:Helvica; font-size:20px; ">    
You can specify the data type of a NumPy array when creating it, or you can check and convert the data type after the array has been created.
<p style="font-family:Helvica; font-size:20px; ">
<b>Example:</b>

In [6]:
import numpy as np

# Creating a NumPy array with a specified data type
arr = np.array([1.2, 2.3, 3.4], dtype=np.float32)
print("Array:", arr)
print("Data Type:", arr.dtype)  # Output: float32


Array: [1.2 2.3 3.4]
Data Type: float32


<p style="font-family:Helvica; font-size:20px; ">
2.<b> Specifying and Converting Data Types</b>
<p style="font-family:Helvica; font-size:20px; ">
You can specify the data type when you create the array or convert it later using the astype() function.
<p style="font-family:Helvica; font-size:20px; ">
<b>Example:</b>

In [7]:
# Creating an array with a specific data type
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original dtype:", arr.dtype)  # int32

# Converting the array to another type (float)
arr_float = arr.astype(np.float64)
print("Converted dtype:", arr_float.dtype)  # float64


Original dtype: int32
Converted dtype: float64


<p style="font-family:Helvica; font-size:20px; ">
This is especially useful if you need to change between integer, float, or even boolean representations for computation.

<p style="font-family:Helvica; font-size:20px; ">
3.<b> Important NumPy Attributes</b>
<p style="font-family:Helvica; font-size:20px; ">
Several key attributes help you understand the structure and characteristics of a NumPy array:
<p style="font-family:Helvica; font-size:20px; ">
a.<b> .shape</b> (Shape of the Array)
<li style="font-family:Helvica; font-size:20px;">The <b>.shape</b> attribute returns a tuple that represents the dimensions (size in each axis) of the array.</li>
<li style="font-family:Helvica; font-size:20px;">For example, an array with 3 rows and 4 columns will have a shape of (3, 4).</li>
<p style="font-family:Helvica; font-size:20px; ">
<b>Example:</b>

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", arr.shape)


Shape of the array: (2, 3)


<p style="font-family:Helvica; font-size:20px; ">
This tells us the array has 2 rows and 3 columns.
<p style="font-family:Helvica; font-size:20px; ">
b.<b> .ndim</b> (Number of Dimensions)
<li style="font-family:Helvica; font-size:20px;">The <b>.ndim</b> attribute returns the number of dimensions (axes) of the array.</li>
<li style="font-family:Helvica; font-size:20px;">A 1D array (vector) will have ndim=1, a 2D array (matrix) will have ndim=2, and so on.</li>
<p style="font-family:Helvica; font-size:20px; ">
<b>Example:</b>

In [9]:
arr = np.array([1, 2, 3])
print("Number of dimensions:", arr.ndim)

arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("Number of dimensions:", arr_2d.ndim)


Number of dimensions: 1
Number of dimensions: 2


<p style="font-family:Helvica; font-size:20px; ">
c. <b>.size</b> (Total Number of Elements)
<li style="font-family:Helvica; font-size:20px;">The <b>.size</b> attribute returns the total number of elements in the array.
<li style="font-family:Helvica; font-size:20px;">For a 2D array, .size is equal to the product of the dimensions in .shape.
<p style="font-family:Helvica; font-size:20px; ">
    
<b>Example:</b>

In [10]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Total number of elements:", arr.size)


Total number of elements: 6


<p style="font-family:Helvica; font-size:20px; ">
This tells us the array has 6 elements in total.
<p style="font-family:Helvica; font-size:20px; ">
d. <b>.itemsize</b> (Size of Each Element)
<li style="font-family:Helvica; font-size:20px;">The <b>.itemsize</b> attribute returns the size in bytes of each element in the array.
<li style="font-family:Helvica; font-size:20px;">This depends on the data type (dtype). For example, int32 elements use 4 bytes (32 bits), while float64 elements use 8 bytes (64 bits).
<p style="font-family:Helvica; font-size:20px; ">

<b>Example:</b>

In [11]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Size of each element (in bytes):", arr.itemsize)

arr_float = np.array([1.2, 2.3, 3.4], dtype=np.float64)
print("Size of each element (in bytes):", arr_float.itemsize)


Size of each element (in bytes): 4
Size of each element (in bytes): 8


<p style="font-family:Helvica; font-size:20px; ">
This means each int32 element takes 4 bytes, and each float64 element takes 8 bytes.
<p style="font-family:Helvica; font-size:20px; ">
4.<b> Example Combining All Attributes:</b>
<p style="font-family:Helvica; font-size:20px; ">
Here’s a comprehensive example that shows how to use these attributes together:

In [12]:
import numpy as np

# Create a 3x3 array with dtype=int32
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)

# Check the shape, dimensions, total elements, and size of elements
print("Array:\n", arr)
print("Shape:", arr.shape)       # (3, 3)
print("Number of dimensions:", arr.ndim)  # 2
print("Total number of elements:", arr.size)  # 9
print("Size of each element (in bytes):", arr.itemsize)  # 4
print("Data type of array:", arr.dtype)  # int32

# Convert to float64
arr_float = arr.astype(np.float64)
print("Converted dtype:", arr_float.dtype)  # float64


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Total number of elements: 9
Size of each element (in bytes): 4
Data type of array: int32
Converted dtype: float64


<p style="font-family:Helvica; font-size:20px; ">
<b>Key Takeaways:</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;"><b>dtype</b> defines the data type of the array. You can specify or convert the data type using .astype().
<li style="font-family:Helvica; font-size:20px;"><b>shape</b> tells you the structure of the array in terms of rows and columns (or higher dimensions).
<li style="font-family:Helvica; font-size:20px;"><b>ndim</b> gives the number of dimensions of the array.
<li style="font-family:Helvica; font-size:20px;"><b>size</b> tells you how many total elements the array contains.
<li style="font-family:Helvica; font-size:20px;"><b>itemsize</b> indicates how much memory each element occupies based on its data type.
<p style="font-family:Helvica; font-size:20px; ">
These attributes allow you to better understand and manage the structure and memory usage of NumPy arrays.

<p style="font-family:Helvica; font-size:20px; ">
<b>Creating arrays:</b>
<p style="font-family:Helvica; font-size:20px; ">
In NumPy, there are several ways to create arrays, each serving different purposes depending on the data you need. Let’s explore the most commonly used methods: np.array(), np.zeros(), np.ones(), np.arange(), and np.linspace().
<p style="font-family:Helvica; font-size:20px; ">
1.<b> Creating an Array with np.array()</b>
<p style="font-family:Helvica; font-size:20px; ">
np.array() is used to create a NumPy array from a Python list or a list of lists (for multi-dimensional arrays).
It can be used with or without specifying the dtype (data type). If not specified, NumPy will infer the data type based on the input.
<p style="font-family:Helvica; font-size:20px; ">
<b>Example:</b>

In [13]:
import numpy as np

# Creating a 1D array from a Python list
arr_1d = np.array([1, 2, 3, 4])
print("1D Array:", arr_1d)

# Creating a 2D array from a list of lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

# Creating an array with a specified data type (float)
arr_float = np.array([1, 2, 3], dtype=float)
print("Array with specified dtype (float):", arr_float)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array with specified dtype (float): [1. 2. 3.]


<p style="font-family:Helvica; font-size:20px; ">
2.<b> Creating an Array of Zeros with np.zeros()</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;">np.zeros() is used to create an array filled with zeros.
<li style="font-family:Helvica; font-size:20px;">You can specify the shape of the array (e.g., (3, 4) for a 3x4 array) and optionally the data type.
<p style="font-family:Helvica; font-size:20px; ">
<b>Example:</b>

In [14]:
# Create a 1D array of zeros
arr_zeros_1d = np.zeros(5)
print("1D Array of zeros:", arr_zeros_1d)

# Create a 2D array of zeros
arr_zeros_2d = np.zeros((3, 4))
print("2D Array of zeros:\n", arr_zeros_2d)

# Create a 2D array of zeros with specified data type (integer)
arr_zeros_int = np.zeros((2, 2), dtype=int)
print("2D Array of zeros (int):\n", arr_zeros_int)

1D Array of zeros: [0. 0. 0. 0. 0.]
2D Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D Array of zeros (int):
 [[0 0]
 [0 0]]


<p style="font-family:Helvica; font-size:20px; ">
3.<b> Creating an Array of Ones with np.ones()</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;">np.ones() is similar to np.zeros(), but it creates an array filled with ones.
<li style="font-family:Helvica; font-size:20px;">You can specify the shape and data type.
<p style="font-family:Helvica; font-size:20px; ">
    
<b>Example:</b>

In [15]:
# Create a 1D array of ones
arr_ones_1d = np.ones(4)
print("1D Array of ones:", arr_ones_1d)

# Create a 2D array of ones
arr_ones_2d = np.ones((3, 3))
print("2D Array of ones:\n", arr_ones_2d)

# Create a 2D array of ones with specified data type (integer)
arr_ones_int = np.ones((2, 2), dtype=int)
print("2D Array of ones (int):\n", arr_ones_int)


1D Array of ones: [1. 1. 1. 1.]
2D Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2D Array of ones (int):
 [[1 1]
 [1 1]]


<p style="font-family:Helvica; font-size:20px; ">
4.<b> Creating an Array with a Range of Values using np.arange()</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;">np.arange() generates an array with evenly spaced values within a specified interval. It works similarly to Python’s built-in range() function but returns a NumPy array.
<li style="font-family:Helvica; font-size:20px;">You can specify the start, stop, and step values.
<p style="font-family:Helvica; font-size:20px; ">
    
<b>Example:</b>

In [16]:
# Create an array from 0 to 9
arr_range = np.arange(10)
print("Array with values from 0 to 9:", arr_range)

# Create an array from 1 to 10 with a step of 2
arr_range_step = np.arange(1, 10, 2)
print("Array with values from 1 to 9 (step 2):", arr_range_step)

# Create an array of floats
arr_range_float = np.arange(0, 1, 0.2)
print("Array with float step:", arr_range_float)


Array with values from 0 to 9: [0 1 2 3 4 5 6 7 8 9]
Array with values from 1 to 9 (step 2): [1 3 5 7 9]
Array with float step: [0.  0.2 0.4 0.6 0.8]


<p style="font-family:Helvica; font-size:20px; ">
5.<b> Creating an Array with Evenly Spaced Values using np.linspace()</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;">np.linspace() generates an array of evenly spaced numbers over a specified range, but instead of using a step value, you specify the total number of points (num).
<li style="font-family:Helvica; font-size:20px;">Useful when you want to divide an interval into equal parts.
<p style="font-family:Helvica; font-size:20px; ">
    
<b>Example:</b>

In [17]:
# Create an array with 5 evenly spaced numbers between 0 and 1
arr_linspace = np.linspace(0, 1, 5)
print("Array with 5 evenly spaced numbers between 0 and 1:", arr_linspace)

# Create an array with 10 evenly spaced numbers between 0 and 10
arr_linspace_10 = np.linspace(0, 10, 10)
print("Array with 10 evenly spaced numbers between 0 and 10:", arr_linspace_10)

# Include the endpoint
arr_linspace_endpoint = np.linspace(0, 1, 5, endpoint=False)
print("Array without including endpoint:", arr_linspace_endpoint)


Array with 5 evenly spaced numbers between 0 and 1: [0.   0.25 0.5  0.75 1.  ]
Array with 10 evenly spaced numbers between 0 and 10: [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
Array without including endpoint: [0.  0.2 0.4 0.6 0.8]


<p style="font-family:Helvica; font-size:20px; ">
<b>Key Differences Between np.arange() and np.linspace():</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;">np.arange() uses a specified step to create values within the range.
<li style="font-family:Helvica; font-size:20px;">np.linspace() allows you to create a specified number of evenly spaced values between a start and an end point.
<p style="font-family:Helvica; font-size:20px; ">
    
<b>Summary of Array Creation Methods:</b>
<p style="font-family:Helvica; font-size:20px; ">
<li style="font-family:Helvica; font-size:20px;">np.array(): Creates an array from a list or list of lists (multi-dimensional arrays).
<li style="font-family:Helvica; font-size:20px;">np.zeros(): Creates an array filled with zeros of a specified shape.
<li style="font-family:Helvica; font-size:20px;">np.ones(): Creates an array filled with ones of a specified shape.
<li style="font-family:Helvica; font-size:20px;">np.arange(): Creates an array with evenly spaced values based on a step size.
<li style="font-family:Helvica; font-size:20px;">np.linspace(): Creates an array with a specified number of evenly spaced values between two limits.
<p style="font-family:Helvica; font-size:20px; ">
Each method allows you to control the array’s shape, size, and data type, making them powerful tools for initializing data in NumPy.

<p style="font-family:Helvica; font-size:20px; ">
<b>Reshaping arrays:</b>
<p style="font-family:Helvica; font-size:20px; ">
Reshaping arrays in NumPy allows you to change the structure of an array without altering its data. This is particularly useful when you're performing operations that require specific dimensions or when you're organizing data in different shapes. Let's explore three common methods used for reshaping arrays: reshape(), ravel(), and transpose().
<p style="font-family:Helvica; font-size:20px; ">
1.<b> reshape():</b> Changing the Shape of an Array
<li style="font-family:Helvica; font-size:20px;">The .reshape() method allows you to change the shape (or dimensions) of an array. You provide the new shape as a tuple, and NumPy will return a new array with that shape, while keeping the same data.
<li style="font-family:Helvica; font-size:20px;">The total number of elements must remain the same before and after reshaping (i.e., the product of dimensions before reshaping must equal the product after reshaping).
<p style="font-family:Helvica; font-size:20px; ">
    
<b>Example:</b>

In [18]:
import numpy as np

# Create a 1D array of 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)

# Reshape it into a 2D array (2 rows, 3 columns)
arr_reshaped = arr.reshape((2, 3))
print("Reshaped array (2x3):\n", arr_reshaped)

# Reshape it into a 3D array (2x1x3)
arr_reshaped_3d = arr.reshape((2, 1, 3))
print("Reshaped array (2x1x3):\n", arr_reshaped_3d)


Original array: [1 2 3 4 5 6]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped array (2x1x3):
 [[[1 2 3]]

 [[4 5 6]]]
